### PR TITLE
Singledomain deploy

### PR DESCRIPTION
**Pull request by variousred**
https://www.pivotaltracker.com/story/show/83970304
singledomain test client breaks on deploying site
a few things were missing for this to work
user email needed to be passed along through the call chain
some methods referenced were undefined
and some objects were incorrectly manipulated

### CODE REVIEW

**Comment by variousred** [comment]
@bbauer think i can merge this?

**Comment by bbauer** [comment]
I'm going to ask again...do we really want all this logging? Seems really excessive to me...and it's been effecting our Code Climate score. Do we actually use this? Code looks good other than that :+1:

**Comment by variousred** [comment]
I use it every time i have to diagnose a deploy issue

On Wed, Jan 7, 2015 at 11:09 AM, Brian Bauer <notifications@github.com>
wrote:

> I'm going to ask again...do we really want all this logging? Seems really
> excessive to me...and it's been effecting our Code Climate score. Do we
> actually use this? Code looks good other than that [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/G5/g5-content-management-system/pull/542#issuecomment-69073693>
> .
>



-- 
-Michael Mitchell

**Comment by bbauer** [comment]
:+1:

**Pull request merged**
