### PR TITLE
fixes pdf file uploads, creating a default asset category

### PR DESCRIPTION
**Pull request by variousred**
fixes creating a default asset category

https://www.pivotaltracker.com/story/show/87024394

### CODE REVIEW

**Comment by variousred** [comment]
@levibrown @variousred this will need to also be implemented into the orion-cms repo. this is a stopgap fix

**Comment by variousred** [comment]
@bbauer @ceckert

**Comment by ceckert** [comment]
@variousred :shipit:

**Comment by bbauer** [comment]
:+1:

**Comment by ceckert** [comment]
@levibrown @variousred Did this ever get added to the orion-cms app? Seems not, as this has come back up recently. Can you review and let me and Garrett know?

**Pull request merged**
