### PR TITLE
manual redirects

### PR DESCRIPTION
**Pull request by ceckert**
Patch for Berkshire redirect issues.

### CODE REVIEW

**Comment by ceckert** [comment]
@variousred - It's a bit of a hack. But the current solution of waking up every time Berkshire deploys is unsustainable. I will fix this more properly with the Single Domain Single Location pull request.

**Comment by mmitchellg5** [comment]
:shipit:

**Comment by ceckert** [comment]
@variousred can you restart the failing test? Tests pass locally for me.

**Comment by mmitchellg5** [comment]
already done :D travis is having some issues at the moment http://www.traviscistatus.com/

**Pull request merged**
