### PR TITLE
WIP: Fix Deep Clone

### PR DESCRIPTION
**Pull request by ceckert**
Deep clone was only cloning one level deep. This adds recursive cloning.

### CODE REVIEW

**Comment by variousred** [comment]
@ceckert this one failing test remaining might atually be uncovering a real bug. It seems we are creating an extra widget in the clone process.

**Comment by bbauer** [comment]
:+1: once green

**Comment by ceckert** [comment]
Tests are passing locally for me. I think this is a Travis CI false positive.

**Comment by variousred** [comment]
Restarted the build on travis

On Wed, Feb 11, 2015 at 11:44 AM, Chris Eckert <notifications@github.com>
wrote:

> Tests are passing locally for me. I think this is a Travis CI false
> positive.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/G5/g5-content-management-system/pull/551#issuecomment-73950155>
> .
>



-- 
-Michael Mitchell

**Pull request merged**
